pipeline {
    agent any
    tools {
        maven 'mvn' // Ensure this matches the configured Maven version in Jenkins
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/clouddevopstrainer/simple-java-maven-app.git' // Replace with your actual Git repository
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
